export const REGIONS = [
  'West Africa',
  'East Africa',
  'Southern Africa',
  'Central Africa',
  'North Africa',
] as const

export const ERAS = [
  'Pre-Colonial',
  'Colonial',
  'Independence',
  'Modern',
  'Contemporary',
] as const

/** A cause needs at least this many women before it gets a hub page. */
export const CAUSE_HUB_MIN_WOMEN = 3

export const CAUSES = [
  'Accountability',
  'Anti-apartheid',
  'Anti-colonial activism',
  'Anti-colonialism',
  'Anti-colonial resistance',
  'Anti-apartheid activism',
  'Anti-apartheid resistance',
  'Anti-corruption',
  'Anti-pass law resistance',
  'Academic freedom',
  'Arts & culture',
  'Black liberation',
  'Children\'s rights',
  'Civil society',
  'Cultural diplomacy',
  'Cultural identity',
  'Cultural preservation',
  'Democracy',
  'Diplomacy & military strategy',
  'Economic development',
  'Economic reform',
  'Education',
  'Environmental rights',
  'Feminism',
  'Film',
  'Freedom of expression',
  'Gender equality',
  'Gender-based violence',
  'Girls\' education',
  'Global trade & development',
  'Governance',
  'Grassroots organising',
  'Healthcare',
  'Healthcare rights',
  'Human rights',
  'Journalism & free press',
  'Labour rights',
  'Leadership',
  'Literature',
  'Military leadership',
  'Music',
  'Nationalist politics',
  'Nollywood',
  'Northern Nigeria women\'s rights',
  'Pan-Africanism',
  'Pass laws',
  'Peace activism',
  'Peace & humanitarian work',
  'Peace & reconciliation',
  'Political freedom',
  'Political leadership',
  'Political power',
  'Political rights',
  'Post-conflict reconstruction',
  'Public health',
  'Religious & social welfare',
  'Religious leadership',
  'Representation',
  'Rule of law',
  'Scholarship & literature',
  'Science',
  'Social justice',
  'Sovereignty & independence',
  'Spiritual leadership',
  'Sport & empowerment',
  'Transparency & anti-corruption',
  'Women in academia',
  'Women in science',
  'Women in STEM',
  'Women\'s economic empowerment',
  'Women\'s education',
  'Women\'s leadership',
  'Women\'s political leadership',
  'Women\'s political participation',
  'Women\'s rights',
  'Women\'s suffrage',
  'Women\'s visibility',
] as const

export const ARTICLE_CATEGORIES = [
  'History',
  'Concepts',
  'Why It Matters',
  'Profiles',
] as const

export type Region = typeof REGIONS[number]
export type Era = typeof ERAS[number]
export type Cause = typeof CAUSES[number]
export type ArticleCategory = typeof ARTICLE_CATEGORIES[number]
